### ISSUE TITLE
Favourite emoji box taking up too much space

### ISSUE THREAD

**Issue by Jacob29** [AlexFlipnote/Discord_MaterialTheme#2]
The favourite box takes up way too much space even when no favourites has been set, often making it so you cannot use the emoji bar.

![Image](http://i.imgur.com/GoN9oTc.png)

**Comment by AlexFlipnote** [comment]
That's quite odd, it works fine here:
<img src="https://i.mify.pw/3dfaa5.png">

Could you tell me how this came?

**Comment by Jacob29** [comment]
Oh I should probably mention I'm using BetterDiscord so it'll be the Twitch emojis that are causing this

**Comment by AlexFlipnote** [comment]
That might be the issue, yeah.
I could look into the BetterDiscord and see if this can be solved, updating here when it's either fixed or not.

**Comment by AlexFlipnote** [comment]
I can't seem to install BetterDiscord on my PC here, which is bad..
Maybe you should switch to BeautifulDiscord https://github.com/leovoel/BeautifulDiscord
It's quite better, just a bit more advanced

Either way, I will see if I can solve this in the near feature, setting this on hold.

**Comment by AlexFlipnote** [comment]
Alright, I looked more into this, sadly, I can't find any way to solve this issue for now.
What I can see is that you can switch off the option of displaying BetterDiscord emotes on the emote-picker, that would solve it for now.

If you need anything more, contact me on Discord or make a new issue report, thanks for the report.
